sudo: false

language: python

python:
  - 2.7

install:
  - pip install codecov

script:
  - python convert-to-guetzli.py || if [ $? -eq 10 ]; then (exit 0); fi
  - coverage run tests.py

after_success:
  - codecov
